### ISSUE TITLE
Alltube nie działa :(

### ISSUE THREAD

**Issue by CzosnekDev** [podpis/kodi#30]
Witam
Od kilku dni wtyczka Alltube nie potrafi wyświetlić prawidłowo źródeł. Na liście zawsze jest tylko jedno - "alltube.pl"

Jak odtworzyć:
- włącz wtyczkę Alltube
- wybierz w "Filmy Nowe" lub inną kategorię
- wybierz jakikolwiek film
- na liście źródeł jest tylko alltube.pl i nie działa

Spodziewany rezultat:
- na liście źródeł są działające źródła

**Comment by podpis** [comment]
Są zmiany na stronie alltube.tv, dlatego nie działa. Konieczna jest przebudowa wtyczki.

**Comment by xulek** [comment]
[plugin.video.alltube.tv-2.5.4a.zip](https://github.com/podpis/kodi/files/2042708/plugin.video.alltube.tv-2.5.4a.zip)

Szybki fix na filmy :)

**Comment by podpis** [comment]
Xulek, jesteś super! Dziękuję w imieniu użytkowników i moim własnym. Nie mam teraz czasu na zmiany, ale wstawię poprawioną wtyczkę do repo.

**Comment by notoco** [comment]
@xulek - jesteś naprawdę wielki :) FanFilm też poprawiony widzę...

**Comment by kopernik1983** [comment]
No panowie :) szacun. Czapki z głów :)

**Comment by mbebe** [comment]
`def scanEpisodes(url):
    content = getUrl(url)
    tytulik = re.compile('<title>(.*?) - (.*?) - (.*?)</title>').findall(content)
    episodes = re.compile('<li class="episode">\n\t\t\t\t\t\t\t<a href="(.*?)">(.*?)</a>').findall(content)
    out=[]

    for e in episodes:
        season = re.findall('s(\d+)',e[1],flags=re.I)
        season = int(season[0]) if season else ''
        episode = re.findall('e(\d+)',e[1],flags=re.I)
        episode = int(episode[0]) if episode else ''
        one = { 'href'  : getHref(e[0]),
                'season' : season,
                'episode' : episode,
                'mediatype': 'episode',
                'title' : unicodePLchar(tytulik[0][0]+' '+e[1].strip())}
        out.append(one)
    return out`
Na dzialajace seriale. Pozdro.

**Comment by podpis** [comment]
Brawo Mbebe! Dziękuję bardzo. Nasz grono rośnie i jak nie mam czasu inni robią poprawki. Oby tak dalej!

**Comment by xxcriticxx** [comment]
Coś z tym updatem nie tak pokazuje ze jest update robię update ale jestem dalej na ver A i znowu pokazuje ze jest update

**Comment by podpis** [comment]
Poprawione. Kolega zapomniał zmienić w pliku addon.xml wersje wtyczki.

**Comment by podpis** [comment]
@220358krolik Szukanie działa, a jeżeli na stronie alltube.tv pod tym tytułem nie ma linków wtedy i wtyczka żadnych nie znajduje. Bym musiał przy braku linków wprowadzić szukanie alternatywne, np. na szukajce.

**Comment by kashkash18** [comment]
Miło patrzeć jak ludzie sobie tutaj pomagają . Oby tak dalej . Serce się raduje ;)

**Comment by wisiann** [comment]
@podpis, 
A mogl bys to zrobic?
Bylo by super jak by sie samo przelaczalo na szukajke,
Alltube ma duzo pustych

**Comment by 220358krolik** [comment]
Nieprecyzyjnie się w poprzednim poście wyraziłem.
Nie działa wyszukiwanie seriali. Znajduje tytuł a linków nie. Linki są bo sprawdziłem poprzez stronę. (np. Billions, Westworld)
Wyszukiwanie filmów jest OK
Tak jest przynajmniej u mnie

**Comment by xxcriticxx** [comment]
@podpis dalej to samo mam w kolko pokazuje sie ten update na ver b

**Comment by podpis** [comment]
W repo jest ustawione: <addon id="plugin.video.alltube.tv" version="2.5.4c" name="alltube.tv" provider-name="Podpis"> - tak samo jest ustawione we wtyczce z numerem wersji 2.5.4c.
Testowałem u siebie, działa bez zarzutu.
Może nie zrobiłeś aktualizacji na wersje 2.5.4c ?

**Comment by xxcriticxx** [comment]
nope ja nie moge z ver A na B  przeskoczyc. gdzie znajde master zip?

**Comment by xxcriticxx** [comment]
@podpis dobra zalatwilem juz z zipa dzieki za pomoc

**Comment by xulek** [comment]
a z pozycji "Zainstaluj z repozytorium" z menu rozszerzonego wybraliście "Wyszukaj aktualizacje"? Bo Kodi czasami nie łapie od razu zmian w pliku md5 sam i trzeba go popchnąć łokciem :P

**Comment by notoco** [comment]
Robiłem to dzisiaj kilka razy - na repocherry pokazywał mi aktualizację, na moim nie... a na kompie odwrotnie...  IMO github ma jakiś problem

**Comment by notoco** [comment]
Eh... A jakoś od dwóch lat robię tylko wyszukaj aktualizacje i działa... Tylko dziś taki problem

**Comment by wesoly-romek** [comment]
Tak jak pisal @220358krolik lista filmow nie jest pokazywana/tworzona po wyszukiwaniu serialu. Dotyczy to wtyczki 2.5.4c , czyli aktualnej.

**Comment by xxcriticxx** [comment]
@podpis z usa ip serach w ogole nie dziala

http://paste.kodi.tv/gowepetuna

**Comment by xxcriticxx** [comment]
@wisiann zrobisz test please

**Comment by wisiann** [comment]
Ano nie dziala 
Wyskakuje errors

**Comment by wisiann** [comment]
Log do wgladu,

https://paste.kodi.tv/xivatasebo

**Comment by wisiann** [comment]
Wogule jakos ta zakladka na seriale dziwnie dziala,nie ma pzycji listy seriali a na seriale filter cokolwiek bys nie robil to wyskakuje tylko jedna i ta sama strona,i nie mozna przezucic na nastepna,

Moze to tylko u mnie?

**Comment by xxcriticxx** [comment]
@wisiann u mnie tak samo jest tylko strona nie ma next page tak jak na filmach

Raportowałem to dla @podpis dawno temu

**Comment by wisiann** [comment]
Moze Prezes cos zaradzi w wolnej chwili?😉

**Comment by mbebe** [comment]
Zobaczcie na te wersje. Wylaczone sortowanie. Szukanie seriali pokazuje linki.
[plugin.video.alltube.tv-2.5.4d.zip](https://github.com/podpis/kodi/files/2065984/plugin.video.alltube.tv-2.5.4d.zip)

**Comment by wisiann** [comment]
@mbebe,dalej to samo jak przedtem,
W serialach pikazuje tylko jedno strone 
Szukanie wyskakuje dalej errors

**Comment by mbebe** [comment]
U mnie dziala.
Seriale(linki) nowe:
![seriale](https://user-images.githubusercontent.com/30195202/40887713-d73253c8-674c-11e8-977a-fe9feb0f54c0.jpg)

Szukanie gomorra:
![seriale-wyszuk1](https://user-images.githubusercontent.com/30195202/40887718-e0fc8de2-674c-11e8-9178-79fe362472c9.jpg)

I po kliku w serial:
![serial-2](https://user-images.githubusercontent.com/30195202/40887720-e9fd6ec0-674c-11e8-94a2-36c098369fa3.jpg)

Daj logi jeszcze.

**Comment by xxcriticxx** [comment]
@mbebe przetestuj a us ip/vpn

**Comment by xxcriticxx** [comment]
@mbebe http://paste.kodi.tv/nidocihude

**Comment by wisiann** [comment]
@xxcriticxx nie myslisz ze to dziwne ze filmy dzialaja dobrze a seriale i szukanie nie?
Jak by byla blokada na US to na cala wtyczke mysle sobie?

**Comment by wisiann** [comment]
log,

https://paste.kodi.tv/izonaloyax

**Comment by xxcriticxx** [comment]
@wisiann problemem jest cloudflare + reCAPTCHA

**Comment by kashkash18** [comment]
@mbebe w PL śmiga aż miło :) dzięki wielkie

**Comment by wisiann** [comment]
@kashkash18,troche zazdroszcze 😉

**Comment by xxcriticxx** [comment]
@wisiann robiles test z pl vpn?

**Comment by 220358krolik** [comment]
Potwierdzam, że wyszukiwanie seriali od początku do końca działa prawidłowo

**Comment by podpis** [comment]
Linki nie działają, bo zamiast linków do filmu ładuje link do obrazka. Nie miałem czasu tego porawiać.

**Comment by podpis** [comment]
Wtyczka alltube porawiona. Był problem z poprawnym wczytywaniem źródeł. W miejsce linka do filmu(serialu) wczytywało obrazek!
Do tego zmieniłem usługę proxy dla USA, gdyż przez webproxy nieprawidłowo wczytywał strony. Zmieniłem to na statyczny proxy, a testy z IP z USA wypadły bardzo poprawnie. Zobaczymy jak długo będzie działać.  Może potem zrobię automatyczny wybór proxy i indywidualne proxy w ustawieniach, podobnie jak we wtyczce TVP.pl.

**Comment by 220358krolik** [comment]
**podpis** Poprawione. Kolega zapomniał zmienić w pliku addon.xml wersje wtyczki.
Chyba znowu zapomniał bo wtyczka po aktualizacji ciągle ma status "dostępna aktualizacja"

**Comment by podpis** [comment]
Poprawione!

**Comment by wisiann** [comment]
@podpis, jaka wersja?bo mi zrobilo update to wersji "c" i wszystko przestalo dzialac

**Comment by podpis** [comment]
Testowałem to na IP z USA. W tym czasie działało. Może proxy jest w tej chwili down. Dlatego wprowadzę w ustawieniach maskę proxy, gdzie będzie można wpisywać własne proxy. Innej rady chyba nie ma.

**Comment by xxcriticxx** [comment]
@podpis gitara potestujemy zobaczymy

zobaczymy czy @wisiann da rade zrobic test

**Comment by wisiann** [comment]
Niestety nic,

Log

Https://paste.kodi.tv/jagukupudi

**Comment by xxcriticxx** [comment]
@wisiann puste filmy i seriale?

**Comment by podpis** [comment]
Jeżeli macie firewall, tak jak ja w pracy i wszystkie porty są blokowane, to nie będzie działać! Pokazuje błąd JSon decoder, gdyż nie ładuje strony z kodem JSon. Obecnie potrzeby port dla proxy to 3128, i ten musi być na firewallu udostępniony.

**Comment by wisiann** [comment]
Puste i wyskakuje errors  przy wszyskim

**Comment by podpis** [comment]
Patrz wpis powyżej.

**Comment by wisiann** [comment]
Ja jade do pracy i testuje na android phone

**Comment by podpis** [comment]
Być może teraz jest proxy down. Spróbuj później.

**Comment by wisiann** [comment]
No problem

**Comment by mbebe** [comment]
`                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests
                                            Traceback (most recent call last):
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alltube.tv/main.py", line 376, in <module>
                                                listMovies(ex_link,page)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alltube.tv/main.py", line 96, in listMovies
                                                out,pagination = alltube.scanMainpage(url,int(page),data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alltube.tv/resources/lib/alltube.py", line 75, in scanMainpage
                                                content = getUrl(url,data)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alltube.tv/resources/lib/alltube.py", line 24, in getUrl
                                                content = getUrlh(url,data,cookies)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.alltube.tv/resources/lib/alltube.py", line 45, in getUrlh
                                                import requests
                                            ImportError: No module named requests`

nie ma import requests w alltube.py i main.py

**Comment by wisiann** [comment]
Mam traffic anyway  :(
Wersja 254d dziala 
Wersja 255 wywala errors przy kazdej pozycji

**Comment by podpis** [comment]
To zdecydujcie się w końcu. Raz mówicie, że nie działa na webproxy, teraz że przedtem było lepiej. Zmieniłem na statyczne proxy, teraz okazuje się, że przedtem było wszystko dobrze, a teraz jest źle. Testowałem na wszystkie mi dostępne sposoby i po zmianach chodziła wtyczka na IP z USA jak burza, o wiele lepiej niż na webproxy. Najlepiej zrobię opcję w ustawieniach i tam będziecie wpisywać swoje proxy ręcznie.

**Comment by podpis** [comment]
@mbebe Nie masz zainstalowanego dodatku requests! To już jest standard w Kodi!

**Comment by wisiann** [comment]
@podpis, ver 254d dzialala zawsze ale nie poprawiala bledow z poprzednich wersji,tz. "szukaj nie dziala i pozycja seriale nie pokazuje nastepnej strony,
Ver 255 nie dziala wogule u mnie,
Jak dla mnie to moze zostac 254d i gitara,
Seriale moge ogladac gdzie indziej ,alltube uzywam tylko do fimow,ale jak robiliscie zmiany to testowalem na US i mowilem co jest grane,
Nie umiem tobie powiedziec dlaczego u ciebie dziala a u mnie nie?

**Comment by xxcriticxx** [comment]
@wisiann cloudflare

**Comment by wisiann** [comment]
No to jak claudflare to kicha,i trzeba sie cieszyc co sie ma

**Comment by podpis** [comment]
No ale po to wprowadziłem statyczne proxy i przy użyciu kilku IP z USA wtyczka śmiga u mnie aż się patrzy. Owszem, zapomniałem wprowadzić zależności requests w addon.xml. Macie to poprawione w wersji 2.5.5a. Na weekend wprowadzę opcję w ustawieniach i tam będziecie mieli możliwość wypróbowania innego proxy z poza USA. Nie wie czemu jest blokada tylko na USA, ale jest. Każde inne IP  nie są blokowane.

**Comment by wisiann** [comment]
#podpis ,ver 2.5.5a juz nie wyrzuca bledu tylko po wejsciu z filmy/seriale jest pusto,
Czemu to dalej nie bangla to nie wiem? Ty masz troche wiecej wiedzy o tym :)

**Comment by xxcriticxx** [comment]
@podpis ver 2.5.5a filmy i seriale puste tak jak @wisiann pisal

**Comment by podpis** [comment]
Wrzucam wersję alpha wtyczki z dodaną opcją proxy w ustawieniach. Standardowo, bez włączonego statycznego proxy, wtyczka używa dla USA webproxy. Po włączeniu proxy w ustawieniach można wprowadzać własne serwery proxy lub użyć ustawień default. Testujcie ją na różnych serwerach proxy, zanim wstawię ją do repo.    
[plugin.video.alltube.tv-2.5.6.zip](https://github.com/podpis/kodi/files/2077259/plugin.video.alltube.tv-2.5.6.zip)

**Comment by wisiann** [comment]
@podpis,
Na webproxy wyswietla poprawnie filmy  
Seriale tylko jedna strone,
Szukaj zaczelo dzialac ale pod wyszukanymi pozycjami wyrzuca ze nie ma zrodel 

Na statycznym proxy przy ustawieniu default pozycja filmy /seriale/szukaj jest pusta 
Po wpisaniu paru innych proxy jest to samo,

Jak dla mnie to moze zostac na web proxy tylko zeby jeszcze poprawic zakladke Szukaj zeby wyszukiwala zrodla  
Oczywiscie opcia statycznego proxy moze zostac we wtyczce

**Comment by rekin65** [comment]
Witam. Posiadam aplikację SPMC na androida. Przedwczoraj po zainstalowaniu wtyczki wszystko pięknie śmigało, wczoraj niestety padło alltube.tv niekompatybilność dodatku, dziś z kolei błąd szukaniu.tv. Proszę o pomoc jak dla prawdziwego laika. Dzięki

**Comment by podpis** [comment]
@rekin65 Proszę o loga. Bez tego nie da się pomóc.

**Comment by podpis** [comment]
@wisiann Prawdopodobnie po zmianie na stronie alltube.tv odpala blokada Cloudflare też przy wczytywaniu linków do filmów, a tego nie było przedtem. To może być przyczyną problemów. Nie mam teraz czasu na poprawki, gdyż wyjeżdżam na parę dni. Może pokombinuję trochę z tym na weekend. W każdym bądź razie statyczne proxy u mnie działa jak trzeba, webproxy działa tylko czasami dobrze - zależy od obciążenia.

**Comment by wisiann** [comment]
Spoko ..poczekamy

**Comment by podpis** [comment]
Blokada Cloudflare wczytuje z header "X_FORWARDED_FOR", dlatego statyczne proxy nie chce działać! Tyle udało mi się do tej pory ustalić.

**Comment by xxcriticxx** [comment]
@podpis nie da rady tego przepuscic przez jakis vps w polandzie?

**Comment by wisiann** [comment]
Te cloudflare to wrzod na du..pe ,normalni ludzie nie moga telewizji poogladac :)

**Comment by xxcriticxx** [comment]
ver 2.5.6

mam tak samo jak pisal @wisiann 

> @podpis,
Na webproxy wyswietla poprawnie filmy
Seriale tylko jedna strone,
Szukaj zaczelo dzialac ale pod wyszukanymi pozycjami wyrzuca ze nie ma zrodel

> Na statycznym proxy przy ustawieniu default pozycja filmy /seriale/szukaj jest pusta

**Comment by podpis** [comment]
Wygląda na to, że używanie wtyczki alltube.tv przez proxy nie ma sensu. Przez webproxy działa różnie. Testowałem wtyczkę pod windowsem i VPN Windscribe. Po ustawieniach na UK lub Norwegię, Niemcy, Szwajcarię, Hong Kong wtyczka działa rewelacyjnie. Podobne testy przeprowadzałem na Androidzie. Proszę to przetestować to u siebie. Ja za to będę mógł zająć się wtyczkami LivePolishTV i Ekstraklasa.

**Comment by kashkash18** [comment]
@podpis no to czekamy na nowe wtyczki :)

**Comment by wisiann** [comment]
@kashkash18 filmbwebbooster jast slaba,ma duzo pozycji ale pod wyszukiwanymi tematami bardzo czesto brakowalo linkow,przynajmiej w US nie wiem jak Polsce ?alltube ,nasze-kino,fanfilm  ogarnia sytuacje i moim zdaniem ta wtyczka nic nie wniesie nowego,
Lepiej sie zajac livepolish tv poniewasz brakuje takiej wtyczki

**Comment by kashkash18** [comment]
Filmwebbooster w PL śmigał elegancko , a do tego ma jedną wielką zaletę "Dziś w Telewizji " która opiera się na polskiej TV.

**Comment by notoco** [comment]
@kashkash18 trwają prace nad włączeniem tej właśnie funkcji do FanFilm...

**Comment by kashkash18** [comment]
@notoco takie wieści bardzo mi się podobają . Rozmawialiśmy kiedyś na ten temat , ale myślałem że temat umarł. W takim układzie czekam spokójnie na tą funkcję .

**Comment by podpis** [comment]
Pracuję teraz na wtyczkę LivePolishTV. Będą inne źródła, ale nie jętki jednodniówki jak za Ramica. Zresztą inne strony i tak "pożyczają" źródła z innych stron i nie ma sensu ich wprowadzać we wtyczce.
Na Filmbooster nie ma teraz czasu. Pewnie kiedyś ją rozkoduję i zdubluje inne wtyczki, ale nie teraz.

**Comment by kashkash18** [comment]
Rozumiem , w takim układzie czekamy na LiveTv i Ekstraklase :)

**Comment by wisiann** [comment]
@kashkash w tym masz racje ,"dzis w telewizji" jest fajne ,to chyba jedna z zakladek ktora lubie,
