### ISSUE TITLE
ekinotv w 100% zrekonstruowana

### ISSUE THREAD

**Issue by mbebe** [podpis/kodi#54]
2.0
- decoding the plugin code
- reconstruction of variable names and names functions
- remove of malicious codes from the plugin
- remove of script.module.ramic from the plugin
- code fixes
- remove of unnecessary modules and functions from the plugin
- search with cloudflare fix

[plugin.video.ekinotv-2.0.zip](https://github.com/podpis/kodi/files/2243061/plugin.video.ekinotv-2.0.zip)

do testowania.

**Comment by Janasek** [comment]
Dzięki

**Comment by xxcriticxx** [comment]
@mbebe `requests` zamontowalem ale poprawnej ver `cfscrape` nie moge znalezc

```
07:09:50.571 T:6804  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.13
07:09:50.584 T:6804   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named requests.sessions
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.ekinotv\addon.py", line 10, in <module>
                                                import ekinotvpl as ekinotv
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.ekinotv\ekinotvpl.py", line 6, in <module>
                                                import cfscrape
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.ekinotv\cfscrape.py", line 8, in <module>
                                                from requests.sessions import Session
                                            ImportError: No module named requests.sessions
                                            -->End of Python script error report<--
07:09:50.613 T:9852   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ekinotv/
07:09:50.613 T:9852   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ekinotv/) failed
```

**Comment by mbebe** [comment]
poprawka do szukania i sprawdz te wersje.

[plugin.video.ekinotv-2.0.1.zip](https://github.com/podpis/kodi/files/2274461/plugin.video.ekinotv-2.0.1.zip)

**Comment by xxcriticxx** [comment]
```
10:12:15.207 T:1040  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.13
10:12:22.599 T:4444  NOTICE: Previous line repeats 1 times.
10:12:22.599 T:4444   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: list indices must be integers, not str
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.ekinotv\addon.py", line 126, in <module>
                                                getFilmy(kateg,wersja,page,ex_link)
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.ekinotv\addon.py", line 75, in getFilmy
                                                addLinkItem(name=p['title'],url=p['href'],mode='ChooseAndPlay',l1_ef_=p['img'],infoLabels=p,fanart=p['img'])
                                            TypeError: list indices must be integers, not str
                                            -->End of Python script error report<--
10:12:22.667 T:9852   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ekinotv/?ex_link=None&foldername=Filmy%20HD&kat=35&mode=filmy&page=1&wer=Lektor%2cDubbing%2cENG%2cPL
10:12:22.667 T:9852   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ekinotv/?ex_link=None&foldername=Filmy%20HD&kat=35&mode=filmy&page=1&wer=Lektor%2cDubbing%2cENG%2cPL) failed
10:12:23.024 T:9608  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.13
10:12:37.100 T:9920  NOTICE: Previous line repeats 2 times.
10:12:37.100 T:9920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'list' object has no attribute 'get'
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.ekinotv\addon.py", line 147, in <module>
                                                addDir(p.get('title'),ex_link=p.get('href'),mode='epizody',infoLabels=p,iconImage=p.get('img'))
                                            AttributeError: 'list' object has no attribute 'get'
                                            -->End of Python script error report<--
10:12:37.166 T:9852   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.ekinotv/?ex_link=%2fserie%2fcatalog%2f0-9&foldername=0-9%20(%5bCOLOR%20blue%5d1%5b%2fCOLOR%5d)&kat&mode=seriale&page=1&wer
10:12:37.167 T:9852   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ekinotv/?ex_link=%2fserie%2fcatalog%2f0-9&foldername=0-9%20(%5bCOLOR%20blue%5d1%5b%2fCOLOR%5d)&kat&mode=seriale&page=1&wer) failed
10:12:41.459 T:2764  NOTICE: ResolveURL: Initializing ResolveURL version: 5.0.13
```

**Comment by mbebe** [comment]
poprawka
[plugin.video.ekinotv-2.0.2.zip](https://github.com/podpis/kodi/files/2274916/plugin.video.ekinotv-2.0.2.zip)

**Comment by xxcriticxx** [comment]
@mbebe seriale zaczely dzialac filmy dalej error

http://paste.kodi.tv/efirowucug.pl

**Comment by mbebe** [comment]
nie dziala uploading w githubie
pozniej sprobuje wgrac wersje 2.0.3

**Comment by xxcriticxx** [comment]
@mbebe thanks

**Comment by mbebe** [comment]
[plugin.video.ekinotv-2.0.3.zip](https://github.com/podpis/kodi/files/2275872/plugin.video.ekinotv-2.0.3.zip)

**Comment by FXcodi** [comment]
Ekino.tv jest do poprawki, blokada cloudflare.

**Comment by mbebe** [comment]
update u mnie w repo :-)

**Comment by FXcodi** [comment]
Super działa już dobrze. 
Wielkie dzięki za to :)

**Comment by peterc1609** [comment]
Wtyczka dziala ale nie mozna znalezc opcji logowania do konta. Jest na to sposob?

**Comment by cvxcvx** [comment]
Można.prosić o naprawę. Nie można się zalogować poprzez wtyczkę.
