### ISSUE TITLE
freedisc , viderpl w 100% zrekonstruowane.

### ISSUE THREAD

**Issue by mbebe** [podpis/kodi#62]
@xxcriticxx 
[plugin.video.viderpl-1.6.zip](https://github.com/podpis/kodi/files/2300515/plugin.video.viderpl-1.6.zip)
[plugin.video.freedisc.pl-1.5.zip](https://github.com/podpis/kodi/files/2300516/plugin.video.freedisc.pl-1.5.zip)
slabe wtyczki. do sprawdzenia.

**Comment by xxcriticxx** [comment]
@mbebe u mnie freedisc sypie blendami jutro postaram się podać log

**Comment by xxcriticxx** [comment]
@mbebe szukaj error, wybrane + ranking puste

```
07:08:05.396 T:7236   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ValueError'>
                                            Error Contents: No JSON object could be decoded
                                            Traceback (most recent call last):
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.freedisc.pl\main.py", line 221, in <module>
                                                ListMovies(ex_link)
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.freedisc.pl\main.py", line 121, in ListMovies
                                                items=freedisc.search(ex_link.split('|')[-1].strip())
                                              File "C:\Users\kodi\AppData\Roaming\Kodi\addons\plugin.video.freedisc.pl\resources\lib\freedisc.py", line 212, in search
                                                data=json.loads(content)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\__init__.py", line 339, in loads
                                                return _default_decoder.decode(s)
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 364, in decode
                                                obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                              File "C:\Program Files (x86)\Kodi\system\python\Lib\json\decoder.py", line 382, in raw_decode
                                                raise ValueError("No JSON object could be decoded")
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
07:08:05.502 T:6576   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.freedisc.pl/?ex_link&foldername=%5bCOLOR%20green%5dNowe%20Szukanie%5b%2fCOLOR%5d&mode=SzukajNowe&page=1
07:08:05.502 T:6576   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.freedisc.pl/?ex_link&foldername=%5bCOLOR%20green%5dNowe%20Szukanie%5b%2fCOLOR%5d&mode=SzukajNowe&page=1) failed
07:08:05.711 T:4288 WARNING: CSkinInfo: failed to load skin settings
07:08:06.011 T:6576 WARNING: Skin has invalid include: Animation_DialogPopupOpenClose
```

**Comment by mbebe** [comment]
Nie dziala w usa. sprawdz strone. u mnie na vpn usa sama strona nie dziala.

**Comment by leonzawodowiec12** [comment]
Jest możliwość dodania: Allbox.tv, ekinomaniak.tv, kinostacja.pl, cda.pl, segos, kinoman.co, polsat news

**Comment by xxcriticxx** [comment]
@mbebe strona dziala w usa

![capture](https://user-images.githubusercontent.com/15007183/44600623-d0d81800-a7a7-11e8-94a9-8613347910bf.PNG)
